//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ahorro
    {
        public int id_ahorro { get; set; }
        public string tipo_ahorro { get; set; }
        public Nullable<int> valor_ahorro { get; set; }
        public Nullable<int> valor_limite_ahorro { get; set; }
        public Nullable<System.DateTime> fecha_ahorro { get; set; }
        public string fk_rut_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
