//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class gasto
    {
        public int id_gasto { get; set; }
        public string nombre_gasto { get; set; }
        public string tipo_gasto { get; set; }
        public string tipo_pago_gasto { get; set; }
        public Nullable<int> pago_cuotas { get; set; }
        public Nullable<int> valor_gasto { get; set; }
        public Nullable<System.DateTime> fecha_gasto { get; set; }
        public string fk_rut_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
